### ISSUE TITLE
Check the completeness of the participants. 

### ISSUE THREAD

**Issue by intervall-ludger** [renalmri-org/website.github.io#5]
For example, Germany does not yet exist, there would be at least Alexandra to mention.

**Comment by plaresmedima** [comment]
Good point - also the first 5 countries ahve nice little flag icons but the others don't. Probably a markdown trick

**Comment by little-ear** [comment]
just updated the list

regarding the flags -> still looking for a good open source (so that we can use it without fear of copyright issues)

**Comment by little-ear** [comment]
I think that we got all major issues done.
